from backend.src.api.dto.auth_dto import (
    AccessTokenResponse,
    ChangePasswordRequest,
    LogoutRequest,
    LoginRequest,
    LoginRequestDTO,
    RegisterRequestDTO,
    RegisterRequest,
    TokenInfo,
    UserResponse,
    UserUpdateRequest,
    UserUpdateRequestDTO,
)
from backend.src.api.dto.record_dto import (
    DailyRecordRequest,
    DailyRecordRequestDTO,
    DailyRecordResponse,
    DailyRecordUpdateRequestDTO,
    DailyRecordUpdateRequest,
    AppendToRecordRequestDTO,
    AppendToRecordRequest,
    RecordStatusUpdateRequestDTO,
    RecordStatusUpdateRequest,
)
from backend.src.api.dto.report_dto import (
    DailyReportRequest,
    DailyReportRequestDTO,
    DailyReportRequestUpdate,
    DailyReportResponse,
)
from backend.src.api.dto.settings_dto import (
    TaskTypeResponse,
    TaskTypeRequest,
    TaskTypeRequestDTO,
    TaskTypeUpdateRequest,
    TaskTypeUpdateRequestDTO,
    AIProviderResponse,
    AIProviderUpdateRequest,
    AIProviderUpdateRequestDTO,
    AIPreferencesUpdateRequest,
    AIPreferencesUpdateRequestDTO,
    AIPreferencesResponse,
    ExternalSystemResponse,
    ExternalSystemUpdateRequest,
    ExternalSystemUpdateRequestDTO,
    AISettingsUpdateResponse,
)
from backend.src.api.dto.user_dto import UserReadDTO, UserRegistrationDTO, UserUpdateDTO


__all__ = [
    # Report DTOs
    "DailyReportRequest",
    "DailyReportResponse",
    "DailyReportRequestDTO",
    "DailyReportRequestUpdate",
    # Record DTOs
    "DailyRecordRequestDTO",
    "DailyRecordRequest",
    "DailyRecordResponse",
    "DailyRecordUpdateRequestDTO",
    "DailyRecordUpdateRequest",
    "AppendToRecordRequestDTO",
    "AppendToRecordRequest",
    "RecordStatusUpdateRequestDTO",
    "RecordStatusUpdateRequest",
    # User DTOs
    "UserReadDTO",
    "UserRegistrationDTO",
    "UserUpdateDTO",
    # Settings DTOs
    "TaskTypeRequest",
    "TaskTypeResponse",
    "TaskTypeRequestDTO",
    "TaskTypeUpdateRequest",
    "TaskTypeUpdateRequestDTO",
    "AIProviderResponse",
    "AIProviderUpdateRequest",
    "AIProviderUpdateRequestDTO",
    "AIPreferencesUpdateRequest",
    "AIPreferencesUpdateRequestDTO",
    "AIPreferencesResponse",
    "ExternalSystemResponse",
    "ExternalSystemUpdateRequest",
    "ExternalSystemUpdateRequestDTO",
    # Auth DTOs
    "ChangePasswordRequest",
    "LogoutRequest",
    "LoginRequest",
    "LoginRequestDTO",
    "RegisterRequest",
    "RegisterRequestDTO",
    "TokenInfo",
    "UserResponse",
    "UserUpdateRequest",
    "AISettingsUpdateResponse",
    "AccessTokenResponse",
    "UserUpdateRequestDTO",
]
