# Domain-based imports for backward compatibility
from backend.src.api.dto.auth import (
    ChangePasswordRequest,
    LoginRequest,
    RegisterRequest,
    UserUpdateRequest,
    AccessTokenResponse,
    TokenInfo,
    UserResponse,
    LoginRequestDTO,
    RegisterRequestDTO,
    UserUpdateRequestDTO,
)
from backend.src.api.dto.records import (
    DailyRecordRequest,
    DailyRecordUpdateRequest,
    AppendToRecordRequest,
    RecordStatusUpdateRequest,
    DailyRecordResponse,
    DailyRecordWithTaskResponse,
    ExternalTaskInfo,
    DailyRecordRequestDTO,
    DailyRecordUpdateRequestDTO,
    AppendToRecordRequestDTO,
    RecordStatusUpdateRequestDTO,
    LinkTaskRequest,
    LinkTaskRequestDTO,
    ExternalTaskCreateRequest,
    ExternalTaskUpdateRequest,
    ExternalTaskCreateRequestDTO,
    ExternalTaskUpdateRequestDTO,
    ExternalTaskResponse,
)
from backend.src.api.dto.reports import (
    DailyReportRequest,
    DailyReportRequestUpdate,
    DailyReportResponse,
    DailyReportRequestDTO,
    DailyReportRequestUpdateDTO,
)
from backend.src.api.dto.settings import (
    TaskTypeRequest,
    TaskTypeUpdateRequest,
    AIPreferencesUpdateRequest,
    AIProviderUpdateRequest,
    ExternalSystemUpdateRequest,
    TaskTypeResponse,
    AIPreferencesResponse,
    AIModelResponse,
    AIProviderResponse,
    AISettingsUpdateResponse,
    ExternalSystemResponse,
    TaskTypeRequestDTO,
    TaskTypeUpdateRequestDTO,
    AIPreferencesUpdateRequestDTO,
    AIProviderUpdateRequestDTO,
    ExternalSystemUpdateRequestDTO,
)
from backend.src.api.dto.shared import (
    UserReadDTO,
    UserRegistrationDTO,
    UserUpdateDTO,
)

# Re-export everything for backward compatibility
__all__ = [
    # Auth domain
    "ChangePasswordRequest",
    "LoginRequest",
    "RegisterRequest",
    "UserUpdateRequest",
    "AccessTokenResponse",
    "TokenInfo",
    "UserResponse",
    "LoginRequestDTO",
    "RegisterRequestDTO",
    "UserUpdateRequestDTO",
    # Records domain
    "DailyRecordRequest",
    "DailyRecordUpdateRequest",
    "AppendToRecordRequest",
    "RecordStatusUpdateRequest",
    "DailyRecordResponse",
    "DailyRecordWithTaskResponse",
    "ExternalTaskInfo",
    "DailyRecordRequestDTO",
    "DailyRecordUpdateRequestDTO",
    "AppendToRecordRequestDTO",
    "RecordStatusUpdateRequestDTO",
    "LinkTaskRequest",
    "LinkTaskRequestDTO",
    "ExternalTaskCreateRequest",
    "ExternalTaskUpdateRequest",
    "ExternalTaskCreateRequestDTO",
    "ExternalTaskUpdateRequestDTO",
    "ExternalTaskResponse",
    # Reports domain
    "DailyReportRequest",
    "DailyReportRequestUpdate",
    "DailyReportResponse",
    "DailyReportRequestDTO",
    "DailyReportRequestUpdateDTO",
    # Settings domain
    "TaskTypeRequest",
    "TaskTypeUpdateRequest",
    "AIPreferencesUpdateRequest",
    "AIProviderUpdateRequest",
    "ExternalSystemUpdateRequest",
    "TaskTypeResponse",
    "AIPreferencesResponse",
    "AIModelResponse",
    "AIProviderResponse",
    "AISettingsUpdateResponse",
    "ExternalSystemResponse",
    "TaskTypeRequestDTO",
    "TaskTypeUpdateRequestDTO",
    "AIPreferencesUpdateRequestDTO",
    "AIProviderUpdateRequestDTO",
    "ExternalSystemUpdateRequestDTO",
    # Shared
    "UserReadDTO",
    "UserRegistrationDTO",
    "UserUpdateDTO",
]
