"""status to record added

Revision ID: 13c09ed19060
Revises: b16a3b6c8090
Create Date: 2025-07-05 21:33:36.574850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c09ed19060'
down_revision: Union[str, None] = 'b16a3b6c8090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_records', sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='recordstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_records', 'status')
    # ### end Alembic commands ###
