"""

Revision ID: 33fb884ecb15
Revises: f52f64ccf2db
Create Date: 2025-10-14 14:09:14.451211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fb884ecb15'
down_revision: Union[str, None] = 'f52f64ccf2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('ai_provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_provider_id'], ['ai_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('ai_model_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('users_password_hash_key'), 'users', type_='unique')
    op.create_foreign_key(None, 'users', 'ai_models', ['ai_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_unique_constraint(op.f('users_password_hash_key'), 'users', ['password_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'ai_model_id')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
