"""

Revision ID: 3c3e588ff26c
Revises: dd909b8459a8
Create Date: 2025-07-13 18:37:42.667539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3e588ff26c'
down_revision: Union[str, None] = 'dd909b8459a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_providers', sa.Column('encrypted_api_key', sa.String(length=500), nullable=True))
    op.drop_column('user_profiles', 'encrypted_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('encrypted_api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('ai_providers', 'encrypted_api_key')
    # ### end Alembic commands ###
