"""timezone changed

Revision ID: 45c07181fd35
Revises: 09a4bba23e7e
Create Date: 2025-07-05 20:12:05.640585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c07181fd35'
down_revision: Union[str, None] = '09a4bba23e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uk_external_system_task_not_null'), table_name='external_tasks', postgresql_where='(external_id IS NOT NULL)')
    op.create_unique_constraint('uk_external_system_task', 'external_tasks', ['external_system_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uk_external_system_task', 'external_tasks', type_='unique')
    op.create_index(op.f('uk_external_system_task_not_null'), 'external_tasks', ['external_system_id', 'external_id'], unique=True, postgresql_where='(external_id IS NOT NULL)')
    # ### end Alembic commands ###
