"""

Revision ID: 4e3a2a00c659
Revises: b71a5e12bfca
Create Date: 2026-02-25 22:36:08.804948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3a2a00c659'
down_revision: Union[str, None] = 'b71a5e12bfca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_system_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'external_systems', ['external_system_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'external_system_id')
    # ### end Alembic commands ###
