"""

Revision ID: 4e541029527d
Revises: 6b88b705ed37
Create Date: 2025-07-29 22:34:38.593256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e541029527d'
down_revision: Union[str, None] = '6b88b705ed37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='Username for authentication')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Username for authentication')
    # ### end Alembic commands ###
