"""

Revision ID: 5fc8be36db03
Revises: bcd922a6330c
Create Date: 2025-07-10 17:51:11.999208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5fc8be36db03"
down_revision: Union[str, None] = "bcd922a6330c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.Column("ai_auto_process", sa.Boolean(), nullable=False),
        # sa.Column('ai_provider', sa.Enum('CLAUDE', 'OPEN_AI', 'GEMINI', 'GROK', 'LOCAL', name='aiproviders'), nullable=False),
        sa.Column("encrypted_api_key", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.drop_table("user_settings")
    op.drop_table("report_templates")
    op.drop_table("profiles")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("department", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("position", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("profiles_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("profiles_pkey")),
    )
    op.create_table(
        "report_templates",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('report_templates_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("template_content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="report_templates_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="report_templates_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("ai_auto_process", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "ai_provider",
            postgresql.ENUM("CLAUDE", "OPEN_AI", "GEMINI", "GROK", "LOCAL", name="aiproviders"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("encrypted_api_key", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("default_report_template_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["default_report_template_id"],
            ["report_templates.id"],
            name=op.f("user_settings_default_report_template_id_fkey"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_settings_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("user_settings_pkey")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("user_settings_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
