"""initial

Revision ID: 64f30ecc2527
Revises:
Create Date: 2025-06-09 21:06:23.379888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f30ecc2527'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_systems',
    sa.Column('name', sa.String(length=50), nullable=False, comment='System identifier (bitrix, jira, asana)'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='Human-readable name (Bitrix24, Jira Cloud)'),
    sa.Column('api_config', sa.JSON(), nullable=False, comment='API connection settings'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether system is active'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reports',
    sa.Column('report_date', sa.DateTime(), nullable=False, comment='Report date'),
    sa.Column('content', sa.Text(), nullable=False, comment='Generated report content'),
    sa.Column('entries_count', sa.Integer(), nullable=False, comment='Number of included daily records'),
    sa.Column('generated_at', sa.DateTime(), nullable=False, comment='Report generation time'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_date', 'reports', ['report_date'], unique=False)
    op.create_index('ix_reports_generated', 'reports', ['generated_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('external_tasks',
    sa.Column('external_id', sa.Integer(), nullable=False, comment='Task ID in external system'),
    sa.Column('external_system_id', sa.Integer(), nullable=False, comment='Link to external system'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Task title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Task description'),
    sa.Column('status', sa.String(length=100), nullable=False, comment='Task status'),
    sa.Column('external_created_at', sa.DateTime(), nullable=False, comment='Creation date in external system'),
    sa.Column('external_updated_at', sa.DateTime(), nullable=True, comment='Last update in external system'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Completion date'),
    sa.Column('last_sync', sa.DateTime(), nullable=False, comment='Last synchronization with external system'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['external_system_id'], ['external_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_system_id', 'external_id', name='uk_external_system_task')
    )
    op.create_index('ix_external_tasks_status', 'external_tasks', ['status'], unique=False)
    op.create_index('ix_external_tasks_sync', 'external_tasks', ['last_sync'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_records',
    sa.Column('raw_input', sa.Text(), nullable=False, comment='Original developer record'),
    sa.Column('ai_processed', sa.Text(), nullable=True, comment='AI processed version'),
    sa.Column('final_description', sa.Text(), nullable=True, comment='Final description for report'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation time'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='AI processing time'),
    sa.Column('is_processed', sa.Boolean(), nullable=False, comment='Whether processed by AI'),
    sa.Column('is_approved', sa.Boolean(), nullable=False, comment='Whether approved by user'),
    sa.Column('external_task_id', sa.Integer(), nullable=True, comment='Link to external task'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['external_task_id'], ['external_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_records')
    op.drop_table('profiles')
    op.drop_index('ix_external_tasks_sync', table_name='external_tasks')
    op.drop_index('ix_external_tasks_status', table_name='external_tasks')
    op.drop_table('external_tasks')
    op.drop_table('users')
    op.drop_index('ix_reports_generated', table_name='reports')
    op.drop_index('ix_reports_date', table_name='reports')
    op.drop_table('reports')
    op.drop_table('external_systems')
    # ### end Alembic commands ###
