"""

Revision ID: 65be437cb61d
Revises: 6f073995a6fd
Create Date: 2025-08-29 05:51:27.997991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65be437cb61d'
down_revision: Union[str, None] = '6f073995a6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_types', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_types', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Username for authentication')
    op.alter_column('users', 'is_verify',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verify',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Username for authentication')
    op.drop_constraint(None, 'task_types', type_='foreignkey')
    op.drop_column('task_types', 'user_id')
    # ### end Alembic commands ###
