"""

Revision ID: 6f073995a6fd
Revises: 77d554413871
Create Date: 2025-08-28 18:24:10.426670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f073995a6fd'
down_revision: Union[str, None] = '77d554413871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_tasks', sa.Column('user_id', sa.Integer(), nullable=True, comment='ID пользователя'))
    op.create_foreign_key(None, 'external_tasks', 'users', ['user_id'], ['id'])
    op.add_column('reports', sa.Column('user_id', sa.Integer(), nullable=True, comment='User ID'))
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Username for authentication')
    op.alter_column('users', 'is_verify',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verify',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Username for authentication')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'user_id')
    op.drop_constraint(None, 'external_tasks', type_='foreignkey')
    op.drop_column('external_tasks', 'user_id')
    # ### end Alembic commands ###
