"""

Revision ID: 7022d6b40ebe
Revises: df54616e4cec
Create Date: 2025-10-15 13:15:39.505259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7022d6b40ebe'
down_revision: Union[str, None] = 'df54616e4cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('custom_prompt', sa.String(), nullable=True, comment='Custom base prompt'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_prompt')
    # ### end Alembic commands ###
