"""all_tables

Revision ID: 709efdac1e69
Revises:
Create Date: 2025-07-06 09:49:01.087441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '709efdac1e69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_records', 'user_id',
               existing_type=sa.INTEGER(),
               comment='ID пользователя',
               existing_nullable=False)
    op.alter_column('daily_records', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Название задачи/активности',
               existing_nullable=False)
    op.alter_column('daily_records', 'raw_input',
               existing_type=sa.TEXT(),
               comment='Original developer record',
               existing_nullable=False)
    op.alter_column('daily_records', 'ai_processed',
               existing_type=sa.TEXT(),
               comment='AI processed version',
               existing_nullable=True)
    op.alter_column('daily_records', 'final_description',
               existing_type=sa.TEXT(),
               comment='Final description for report',
               existing_nullable=True)
    op.alter_column('daily_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment='Creation time',
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_records', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='AI processing time',
               existing_nullable=True)
    op.alter_column('daily_records', 'is_processed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Whether processed by AI',
               existing_server_default=sa.text('false'))
    op.alter_column('daily_records', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Whether approved by user',
               existing_server_default=sa.text('false'))
    op.alter_column('daily_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('daily_records', 'external_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Quick external task link',
               existing_nullable=True)
    op.alter_column('daily_records', 'external_task_id',
               existing_type=sa.INTEGER(),
               comment='Link to external task',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_records', 'external_task_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Link to external task',
               existing_nullable=True)
    op.alter_column('daily_records', 'external_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Quick external task link',
               existing_nullable=True)
    op.alter_column('daily_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('daily_records', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Whether approved by user',
               existing_server_default=sa.text('false'))
    op.alter_column('daily_records', 'is_processed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Whether processed by AI',
               existing_server_default=sa.text('false'))
    op.alter_column('daily_records', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='AI processing time',
               existing_nullable=True)
    op.alter_column('daily_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Creation time',
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_records', 'final_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Final description for report',
               existing_nullable=True)
    op.alter_column('daily_records', 'ai_processed',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='AI processed version',
               existing_nullable=True)
    op.alter_column('daily_records', 'raw_input',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Original developer record',
               existing_nullable=False)
    op.alter_column('daily_records', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Название задачи/активности',
               existing_nullable=False)
    op.alter_column('daily_records', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID пользователя',
               existing_nullable=False)
    # ### end Alembic commands ###
