"""new field

Revision ID: 7604fa33121c
Revises: 0b36c3255d41
Create Date: 2025-07-02 22:28:30.202053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7604fa33121c'
down_revision: Union[str, None] = '0b36c3255d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_tasks', sa.Column('url', sa.String(length=256), nullable=False, comment='Task link'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_tasks', 'url')
    # ### end Alembic commands ###
