"""

Revision ID: 77d554413871
Revises: 4e541029527d
Create Date: 2025-08-18 22:12:41.748106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d554413871'
down_revision: Union[str, None] = '4e541029527d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=True, comment='Username for authentication'))
    op.add_column('users', sa.Column('is_verify', sa.Boolean(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=50),
               comment='Email for authentication',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=1024),
               comment='Password hash',
               existing_nullable=False)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['name'])
    op.create_unique_constraint(None, 'users', ['password_hash'])
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Username for authentication'))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='Password hash',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=320),
               comment=None,
               existing_comment='Email for authentication',
               existing_nullable=True)
    op.drop_column('users', 'is_verify')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
