"""

Revision ID: 7b727e268c74
Revises: 65be437cb61d
Create Date: 2025-08-29 06:15:53.058138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b727e268c74'
down_revision: Union[str, None] = '65be437cb61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Creation time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_types', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Username for authentication')
    op.alter_column('users', 'is_verify',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verify',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Username for authentication')
    op.alter_column('task_types', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Creation time',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
