"""

Revision ID: 9a94657aeeb9
Revises: 5fc8be36db03
Create Date: 2025-07-13 09:42:32.291434

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a94657aeeb9"
down_revision: Union[str, None] = "5fc8be36db03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_profiles", sa.Column("task_type", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_profiles",
        "ai_provider",
        existing_type=sa.Enum("CLAUDE", "OPEN_AI", "GEMINI", "GROK", "LOCAL", name="aiproviders"),
        type_=sa.VARCHAR(length=256),
        nullable=True,
    )
    op.drop_column("user_profiles", "task_type")
    # ### end Alembic commands ###
