"""

Revision ID: a77bb92dcf55
Revises: 33fb884ecb15
Create Date: 2025-10-14 14:15:08.169559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77bb92dcf55'
down_revision: Union[str, None] = '33fb884ecb15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_models', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('ai_models_name_key'), 'ai_models', type_='unique')
    op.create_unique_constraint('uk_provider_model', 'ai_models', ['ai_provider_id', 'name'])
    op.alter_column('external_systems', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='System identifier (jira, asana)',
               existing_comment='System identifier (bitrix, jira, asana)',
               existing_nullable=False)
    op.alter_column('external_systems', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Human-readable name (Jira Cloud)',
               existing_comment='Human-readable name (Bitrix24, Jira Cloud)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_systems', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Human-readable name (Bitrix24, Jira Cloud)',
               existing_comment='Human-readable name (Jira Cloud)',
               existing_nullable=False)
    op.alter_column('external_systems', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='System identifier (bitrix, jira, asana)',
               existing_comment='System identifier (jira, asana)',
               existing_nullable=False)
    op.drop_constraint('uk_provider_model', 'ai_models', type_='unique')
    op.create_unique_constraint(op.f('ai_models_name_key'), 'ai_models', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('ai_models', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
