"""url added

Revision ID: b16a3b6c8090
Revises: 45c07181fd35
Create Date: 2025-07-05 20:18:55.654683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16a3b6c8090'
down_revision: Union[str, None] = '45c07181fd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_records', sa.Column('external_url', sa.String(length=500), nullable=True, comment='Quick external task link'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_records', 'external_url')
    # ### end Alembic commands ###
