"""

Revision ID: b5e38faaf628
Revises: d82407108afd
Create Date: 2025-11-01 23:39:04.874353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e38faaf628'
down_revision: Union[str, None] = 'd82407108afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='User ID',
               existing_comment='ID пользователя')
    op.alter_column('external_tasks', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Task ID in external system')
    op.alter_column('external_tasks', 'title',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_comment='Task title')
    op.alter_column('reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='User ID')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='Email for authentication')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Email for authentication')
    op.alter_column('reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='User ID')
    op.alter_column('external_tasks', 'title',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_comment='Task title')
    op.alter_column('external_tasks', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Task ID in external system')
    op.alter_column('external_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='ID пользователя',
               existing_comment='User ID')
    # ### end Alembic commands ###
