"""null id

Revision ID: bc821f9d5e6f
Revises: 0a9b38ebfe11
Create Date: 2025-07-03 20:32:09.442496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc821f9d5e6f'
down_revision: Union[str, None] = '0a9b38ebfe11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_tasks', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Task ID in external system')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_tasks', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Task ID in external system')
    # ### end Alembic commands ###
