"""all_tables

Revision ID: c331c3f96b9e
Revises: 2910b66071b4
Create Date: 2025-07-01 20:33:38.558368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "c331c3f96b9e"
down_revision: Union[str, None] = "2910b66071b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ai_providers_enum = postgresql.ENUM('CLAUDE', 'OPEN_AI', 'GEMINI', 'GROK', 'LOCAL', name='aiproviders')
    ai_providers_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "daily_records",
        sa.Column(
            "title", sa.String(length=255), nullable=False, comment="Название задачи/активности"
        ),
    )
    op.alter_column(
        "external_tasks",
        "title",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
        existing_comment="Task title",
    )
    op.alter_column(
        "user_settings",
        "ai_provider",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum("CLAUDE", "OPEN_AI", "GEMINI", "GROK", "LOCAL", name="aiproviders"),
        nullable=False,
        postgresql_using="ai_provider::aiproviders"
    )
    op.alter_column(
        "user_settings", "encrypted_api_key", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_settings", "encrypted_api_key", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "user_settings",
        "ai_provider",
        existing_type=sa.Enum("CLAUDE", "OPEN_AI", "GEMINI", "GROK", "LOCAL", name="aiproviders"),
        type_=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "external_tasks",
        "title",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
        existing_comment="Task title",
    )
    op.drop_column("daily_records", "title")
    ai_providers_enum = postgresql.ENUM('CLAUDE', 'OPEN_AI', 'GEMINI', 'GROK', 'LOCAL', name='aiproviders')
    ai_providers_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
