"""

Revision ID: d82407108afd
Revises: 7022d6b40ebe
Create Date: 2025-10-24 12:13:38.040182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82407108afd'
down_revision: Union[str, None] = '7022d6b40ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_keys',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_provider_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_provider_id'], ['ai_providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ai_provider_id', name='uk_user_provider_key')
    )
    op.create_index('ix_ai_provider_keys_user_active', 'ai_provider_keys', ['user_id', 'is_active'], unique=False)
    op.drop_column('ai_providers', 'encrypted_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_providers', sa.Column('encrypted_api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index('ix_ai_provider_keys_user_active', table_name='ai_provider_keys')
    op.drop_table('ai_provider_keys')
    # ### end Alembic commands ###
