"""user id to daily record added

Revision ID: d9a7ef26615b
Revises: c331c3f96b9e
Create Date: 2025-07-01 20:50:12.647736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a7ef26615b'
down_revision: Union[str, None] = 'c331c3f96b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_records', sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'))
    op.create_foreign_key(None, 'daily_records', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_records', type_='foreignkey')
    op.drop_column('daily_records', 'user_id')
    # ### end Alembic commands ###
