"""

Revision ID: dd909b8459a8
Revises: 9a94657aeeb9
Create Date: 2025-07-13 18:28:03.099670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd909b8459a8"
down_revision: Union[str, None] = "9a94657aeeb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("base_prompt", sa.Text(), nullable=True, comment="Basic system prompt."),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("requires_api_key", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_ai_providers_active", "ai_providers", ["is_active"], unique=False)

    op.execute("""
            INSERT INTO ai_providers (id, name, base_prompt, requires_api_key, is_active) VALUES
            (1, 'local', 'You are a helpful assistant', false, true),
            (2, 'openai', 'You are an AI assistant', true, true),
            (3, 'claude', 'You are Claude AI', true, true)
        """)

    op.create_table(
        "task_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_profile_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_profile_id"],
            ["user_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_profile_id", "title", name="uk_user_profile_task_type"),
    )
    op.create_index(
        "ix_task_types_user_profile_active",
        "task_types",
        ["user_profile_id", "is_active"],
        unique=False,
    )

    op.add_column(
        "user_profiles",
        sa.Column("ai_provider_id", sa.Integer(), nullable=True, server_default="1"),
    )

    op.execute("UPDATE user_profiles SET ai_provider_id = 1 WHERE ai_provider_id IS NULL")

    op.alter_column("user_profiles", "ai_provider_id", nullable=False, server_default=None)

    op.create_foreign_key(None, "user_profiles", "ai_providers", ["ai_provider_id"], ["id"])

    op.drop_column("user_profiles", "ai_provider")
    op.drop_column("user_profiles", "task_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles",
        sa.Column("task_type", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user_profiles",
        sa.Column("ai_provider", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "user_profiles", type_="foreignkey")
    op.drop_column("user_profiles", "ai_provider_id")
    op.drop_index("ix_task_types_user_profile_active", table_name="task_types")
    op.drop_table("task_types")
    op.drop_index("ix_ai_providers_active", table_name="ai_providers")
    op.drop_table("ai_providers")
    # ### end Alembic commands ###
