"""

Revision ID: df54616e4cec
Revises: a77bb92dcf55
Create Date: 2025-10-14 19:24:29.681165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df54616e4cec'
down_revision: Union[str, None] = 'a77bb92dcf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_providers', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_providers', sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
