"""profile updated

Revision ID: ece3c1289cf0
Revises: c83b2b0c9380
Create Date: 2025-07-08 16:04:33.470392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece3c1289cf0'
down_revision: Union[str, None] = 'c83b2b0c9380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('position', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'position')
    op.drop_column('profiles', 'department')
    # ### end Alembic commands ###
