"""

Revision ID: f52f64ccf2db
Revises: b2f0e7fc4f26
Create Date: 2025-09-10 19:11:57.873040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f52f64ccf2db'
down_revision: Union[str, None] = 'b2f0e7fc4f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE user_profiles CASCADE')
    op.alter_column('task_types', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_task_types_user_profile_active'), table_name='task_types')
    op.drop_constraint(op.f('uk_user_profile_task_type'), 'task_types', type_='unique')
    op.create_index('ix_task_types_user_active', 'task_types', ['user_id', 'is_active'], unique=False)
    op.create_unique_constraint('uk_user_task_type', 'task_types', ['user_id', 'title'])
    op.drop_column('task_types', 'user_profile_id')
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('ai_auto_process', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('ai_provider_id', sa.Integer(), nullable=True))
    op.execute("UPDATE users SET name = 'user_' || id WHERE name IS NULL")
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='Username for authentication')
    op.execute("UPDATE users SET is_verify = false WHERE is_verify IS NULL")
    op.alter_column('users', 'is_verify',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'ai_providers', ['ai_provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verify',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='Username for authentication')
    op.drop_column('users', 'ai_provider_id')
    op.drop_column('users', 'ai_auto_process')
    op.drop_column('users', 'position')
    op.drop_column('users', 'department')
    op.drop_column('users', 'display_name')
    op.add_column('task_types', sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('task_types_user_profile_id_fkey'), 'task_types', 'user_profiles', ['user_profile_id'], ['id'])
    op.drop_index('ix_task_types_user_active', table_name='task_types')
    op.create_unique_constraint(op.f('uk_user_profile_task_type'), 'task_types', ['user_profile_id', 'title'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_task_types_user_profile_active'), 'task_types', ['user_profile_id', 'is_active'], unique=False)
    op.alter_column('task_types', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ai_auto_process', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('ai_provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ai_provider_id'], ['ai_providers.id'], name=op.f('user_profiles_ai_provider_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
