from backend.src.presentation.dto.auth import (
    AccessTokenResponse,
    ChangePasswordRequest,
    LoginRequest,
    LoginRequestDTO,
    RegisterRequest,
    RegisterRequestDTO,
    TokenInfo,
    UserResponse,
    UserUpdateRequest,
    UserUpdateRequestDTO,
)
from backend.src.presentation.dto.records import (
    AppendToRecordRequest,
    AppendToRecordRequestDTO,
    DailyRecordRequest,
    DailyRecordRequestDTO,
    DailyRecordResponse,
    DailyRecordUpdateRequest,
    DailyRecordUpdateRequestDTO,
    DailyRecordWithTaskResponse,
    ExternalTaskCreateRequest,
    ExternalTaskCreateRequestDTO,
    ExternalTaskInfo,
    ExternalTaskResponse,
    ExternalTaskUpdateRequest,
    ExternalTaskUpdateRequestDTO,
    LinkTaskRequest,
    LinkTaskRequestDTO,
    RecordStatusUpdateRequest,
    RecordStatusUpdateRequestDTO,
)
from backend.src.presentation.dto.reports import (
    DailyReportRequest,
    DailyReportRequestDTO,
    DailyReportRequestUpdate,
    DailyReportRequestUpdateDTO,
    DailyReportResponse,
)
from backend.src.presentation.dto.settings import (
    AIModelResponse,
    AIPreferencesResponse,
    AIPreferencesUpdateRequest,
    AIPreferencesUpdateRequestDTO,
    AIProviderResponse,
    AIProviderUpdateRequest,
    AIProviderUpdateRequestDTO,
    AISettingsUpdateResponse,
    ExternalSystemResponse,
    ExternalSystemUpdateRequest,
    ExternalSystemUpdateRequestDTO,
    TaskTypeRequest,
    TaskTypeRequestDTO,
    TaskTypeResponse,
    TaskTypeUpdateRequest,
    TaskTypeUpdateRequestDTO,
)
from backend.src.presentation.dto.shared import UserReadDTO, UserRegistrationDTO, UserUpdateDTO

__all__ = [
    # Auth domain
    "ChangePasswordRequest",
    "LoginRequest",
    "RegisterRequest",
    "UserUpdateRequest",
    "AccessTokenResponse",
    "TokenInfo",
    "UserResponse",
    "LoginRequestDTO",
    "RegisterRequestDTO",
    "UserUpdateRequestDTO",
    # Records domain
    "DailyRecordRequest",
    "DailyRecordUpdateRequest",
    "AppendToRecordRequest",
    "RecordStatusUpdateRequest",
    "DailyRecordResponse",
    "DailyRecordWithTaskResponse",
    "ExternalTaskInfo",
    "DailyRecordRequestDTO",
    "DailyRecordUpdateRequestDTO",
    "AppendToRecordRequestDTO",
    "RecordStatusUpdateRequestDTO",
    "LinkTaskRequest",
    "LinkTaskRequestDTO",
    "ExternalTaskCreateRequest",
    "ExternalTaskUpdateRequest",
    "ExternalTaskCreateRequestDTO",
    "ExternalTaskUpdateRequestDTO",
    "ExternalTaskResponse",
    # Reports domain
    "DailyReportRequest",
    "DailyReportRequestUpdate",
    "DailyReportResponse",
    "DailyReportRequestDTO",
    "DailyReportRequestUpdateDTO",
    # Settings domain
    "TaskTypeRequest",
    "TaskTypeUpdateRequest",
    "AIPreferencesUpdateRequest",
    "AIProviderUpdateRequest",
    "ExternalSystemUpdateRequest",
    "TaskTypeResponse",
    "AIPreferencesResponse",
    "AIModelResponse",
    "AIProviderResponse",
    "AISettingsUpdateResponse",
    "ExternalSystemResponse",
    "TaskTypeRequestDTO",
    "TaskTypeUpdateRequestDTO",
    "AIPreferencesUpdateRequestDTO",
    "AIProviderUpdateRequestDTO",
    "ExternalSystemUpdateRequestDTO",
    # Shared
    "UserReadDTO",
    "UserRegistrationDTO",
    "UserUpdateDTO",
]
