from backend.src.presentation.dto.auth.responses import AccessTokenResponse, UserResponse
from backend.src.presentation.dto.records import (
    AppendToRecordRequestDTO,
    DailyRecordRequestDTO,
    DailyRecordResponse,
    DailyRecordUpdateRequestDTO,
    DailyRecordWithTaskResponse,
    ExternalTaskCreateRequestDTO,
    ExternalTaskInfo,
    ExternalTaskResponse,
    ExternalTaskUpdateRequestDTO,
    LinkTaskRequestDTO,
    RecordStatusUpdateRequestDTO,
)
from backend.src.presentation.dto.reports import (
    ReportRequestDTO,
    ReportRequestUpdateDTO,
    ReportResponse,
)
from backend.src.presentation.dto.settings import (
    AIModelResponse,
    AIPreferencesResponse,
    AIPreferencesUpdateRequestDTO,
    AIProviderResponse,
    AIProviderUpdateRequestDTO,
    AISettingsUpdateResponse,
    ExternalSystemResponse,
    ExternalSystemUpdateRequestDTO,
    TaskTypeRequestDTO,
    TaskTypeResponse,
    TaskTypeUpdateRequestDTO,
)
from backend.src.presentation.dto.shared import UserReadDTO, UserRegistrationDTO, UserUpdateDTO

__all__ = [
    # Auth domain
    "LoginRequest",
    "RegisterRequest",
    "UserUpdateRequest",
    "AccessTokenResponse",
    "TokenInfo",
    "UserResponse",
    "LoginRequestDTO",
    "RegisterRequestDTO",
    "UserUpdateRequestDTO",
    # Records domain
    "DailyRecordResponse",
    "DailyRecordWithTaskResponse",
    "ExternalTaskInfo",
    "DailyRecordRequestDTO",
    "DailyRecordUpdateRequestDTO",
    "AppendToRecordRequestDTO",
    "RecordStatusUpdateRequestDTO",
    "LinkTaskRequest",
    "LinkTaskRequestDTO",
    "ExternalTaskCreateRequest",
    "ExternalTaskUpdateRequest",
    "ExternalTaskCreateRequestDTO",
    "ExternalTaskUpdateRequestDTO",
    "ExternalTaskResponse",
    # Reports domain
    "ReportResponse",
    "ReportRequestDTO",
    "ReportRequestUpdateDTO",
    # Settings domain
    "TaskTypeRequest",
    "TaskTypeUpdateRequest",
    "AIPreferencesUpdateRequest",
    "AIProviderUpdateRequest",
    "ExternalSystemUpdateRequest",
    "TaskTypeResponse",
    "AIPreferencesResponse",
    "AIModelResponse",
    "AIProviderResponse",
    "AISettingsUpdateResponse",
    "ExternalSystemResponse",
    "TaskTypeRequestDTO",
    "TaskTypeUpdateRequestDTO",
    "AIPreferencesUpdateRequestDTO",
    "AIProviderUpdateRequestDTO",
    "ExternalSystemUpdateRequestDTO",
    # Shared
    "UserReadDTO",
    "UserRegistrationDTO",
    "UserUpdateDTO",
]
