from collections.abc import Sequence
from datetime import date
from typing import Any, Protocol

from backend.src.application.dto.auth import RegisterData
from backend.src.application.dto.records import DailyRecordData, ExternalTaskCreateData
from backend.src.application.dto.reports import ReportUpdateData
from backend.src.application.dto.settings import ExternalSystemUpdateData
from backend.src.domain.entities.ai import AIProvider, AIProviderKey
from backend.src.domain.entities.external_system import ExternalSystem
from backend.src.domain.entities.external_task import ExternalTask
from backend.src.domain.entities.record import DailyRecord
from backend.src.domain.entities.report import Report
from backend.src.domain.entities.task_type import TaskType
from backend.src.domain.entities.user import User
from backend.src.domain.value_objects import RecordStatus
from backend.src.infrastructure.database.models import AIProviderKeyModel


class IAIProviderRepository(Protocol):
    async def get_many_active(self) -> Sequence[AIProvider]: ...
    async def get_active_providers_with_models(self) -> Sequence[AIProvider]: ...
    async def get_by_id_with_models(self, provider_id: int) -> AIProvider | None: ...
    @property
    def session(self) -> Any: ...


class IAIModelRepository(Protocol):
    @property
    def session(self) -> Any: ...


class IAIProviderKeyRepository(Protocol):
    async def get_user_provider_key(
        self, user_id: int, provider_id: int
    ) -> AIProviderKey | None: ...
    async def add(self, data: AIProviderKeyModel) -> AIProviderKeyModel: ...
    @property
    def session(self) -> Any: ...


class IUserRepository(Protocol):
    async def get_user_by_email(self, email: str) -> User | None: ...
    async def get_user_by_id(self, id: int) -> User | None: ...
    async def create_user(self, data: RegisterData, hashed_password: str) -> User: ...
    async def update_user(self, user: User) -> User: ...
    async def get_one(self, **kwargs: Any) -> Any: ...
    async def get_one_or_none(self, **kwargs: Any) -> Any: ...

    @property
    def session(self) -> Any: ...


class IExternalSystemRepository(Protocol):
    async def get_many(self) -> Sequence[ExternalSystem]: ...
    async def get_by_id(self, system_id: int) -> ExternalSystem | None: ...
    async def get_many_active(self) -> Sequence[ExternalSystem]: ...
    async def update_system(
        self, system_id: int, data: ExternalSystemUpdateData
    ) -> ExternalSystem: ...
    async def get_one(self, **kwargs: Any) -> Any: ...
    async def get_one_or_none(self, **kwargs: Any) -> Any: ...


class IExternalTaskRepository(Protocol):
    """Repository for managing external tasks."""

    async def get_by_external_id(
        self, system_id: int, external_id: int, user_id: int
    ) -> ExternalTask | None: ...

    async def get_tasks_for_sync(self, system_id: int) -> Sequence[ExternalTask]:
        """Get tasks that need synchronization."""
        ...

    async def get_by_id(self, task_id: int, user_id: int) -> ExternalTask | None: ...
    async def get_one(self, **kwargs: Any) -> Any: ...
    async def get_one_or_none(self, **kwargs: Any) -> Any: ...

    async def create_task(
        self, data: ExternalTaskCreateData, user_id: int, system_id: int
    ) -> ExternalTask: ...
    async def update_task(self, task: ExternalTask) -> ExternalTask: ...
    async def delete_task(self, task_id: int, user_id: int) -> None: ...

    @property
    def session(self) -> Any: ...


class IDailyRecordRepository(Protocol):
    async def create_record(self, data: DailyRecordData, user_id: int) -> DailyRecord: ...
    async def get_record(self, record_id: int, user_id: int) -> DailyRecord: ...
    async def update_record(self, entity: DailyRecord) -> DailyRecord: ...
    async def delete_record(self, record_id: int) -> None: ...

    async def get_by_title_user_and_date(
        self, title: str, user_id: int, day: date
    ) -> DailyRecord | None: ...

    async def get_with_external_task(self, record_id: int, user_id: int) -> DailyRecord: ...

    async def get_records_by_date(
        self, target_date: date, user_id: int, include_external_tasks: bool = False
    ) -> Sequence[DailyRecord]: ...

    async def get_unprocessed_records(self, user_id: int) -> Sequence[DailyRecord]: ...

    async def get_records_for_external_task(
        self, external_task_id: int, user_id: int
    ) -> Sequence[DailyRecord]: ...

    async def get_records_by_status(
        self, status: RecordStatus, user_id: int
    ) -> Sequence[DailyRecord]: ...

    async def get_all_records(self, user_id: int) -> Sequence[DailyRecord]: ...

    @property
    def session(self) -> Any: ...


class IReportRepository(Protocol):
    async def get_latest_report(self, user_id: int) -> Report | None: ...

    async def get_reports_by_date_range(
        self, start_date: date, end_date: date, user_id: int
    ) -> Sequence[Report]: ...

    async def update_report(self, update_data: ReportUpdateData, user_id: int) -> Report: ...

    async def get_report(self, report_id: int, user_id: int) -> Report: ...
    async def create_report(self, report_entity: Report) -> Report: ...
    async def list_reports(self, user_id: int | None = None) -> Sequence[Report]: ...
    async def delete_report(self, report_id: int, user_id: int) -> None: ...

    async def delete(self, item_id: Any) -> Any: ...

    @property
    def session(self) -> Any: ...


class ITaskTypeRepository(Protocol):
    """Repository for TaskType operations."""

    async def get_all_for_user(self, user_id: int) -> Sequence[TaskType]: ...
    async def get_by_id_and_user(self, task_type_id: int, user_id: int) -> TaskType: ...
    async def create_for_user(
        self, user_id: int, title: str, color: str | None = None
    ) -> TaskType: ...
    async def update_task_type(
        self,
        task_type_id: int,
        user_id: int,
        title: str | None = None,
        color: str | None = None,
        is_active: bool | None = None,
    ) -> TaskType: ...

    async def delete_task_type(self, task_type_id: int) -> None: ...

    async def delete(self, item_id: Any) -> Any: ...

    @property
    def session(self) -> Any: ...
